# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
include BestInPlace::TestHelpers

# Commonly used webrat steps
# http://github.com/brynary/webrat


When(/^I click "(.*?)" div$/) do |div_ele|
  find("div##{div_ele}").click
end

When(/^I add new token item in "(.*?)" and "(.*?)" as id and "(.*?)" as name$/) do |element_id, token_id, token_name|
  page.driver.browser.execute_script %Q{
   $("#{element_id}").tokenInput("add", {id: "#{token_id}", name: "#{token_name}"});
  }
  sleep(2);
end

When(/^I delete token item in "(.*?)" and "(.*?)" as id$/) do |element_id, token_id|
  page.driver.browser.execute_script %Q{
   $("#{element_id}").tokenInput("remove", {id: "#{token_id}"});
  }
  sleep(2);
end



