# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
include BestInPlace::TestHelpers

# Commonly used webrat steps
# http://github.com/brynary/webrat


When(/^I add row to "(.*?)" grid$/) do |grid_container|
  within(grid_container) do 
    find("span.ui-icon.ui-icon-plus").click
  end
end

When(/^I save row to "(.*?)" grid$/) do |grid_container|
  within(grid_container) do 
    find("span.ui-icon.ui-icon-disk").click
  end
end

#When(/^clicked on "(.*?)"$/) do |link|
#  click_link(link)
#end
#
#When(/^I fill in "(.*?)" with "(.*?)" within "(.*?)"$/) do |field, value, container|
#  within(container) do
#    fill_in(field, :with => value)
#  end
#end






